typography_spectrum: 0.2712
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.24159828363917768
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75851
analytics:
  google: UA-81189378-1
  facebook: null
  twitter: null
name: Marnix De Cat
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Marnix
    id: 7e95c9e1-b22a-407c-83f5-f527d2b1729d
    type: content
  - name: Pluto & Hathor
    id: 932aaf48-6880-48b2-aec8-bb0d469cafad
    type: content
  - name: GCA
    id: 97b996bf-a214-42fb-95cb-9b29ad7fd766
    type: content
  - name: Impro organ & sax
    id: f10743e4-c6b1-4e7f-94e4-7f45cde81707
    type: content
favicon: null
title: Marnix De Cat
purpose: []
