typography_spectrum: 0.2712
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.24159828363917768
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50193
analytics:
  google: UA-81189378-1
  facebook: null
  twitter: null
name: Marnix De Cat
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: bc5bd4a3-d7f9-4d20-b40d-ee6e9cfa0bfa
    url: 2016-07-20-composer.html
    name: Composer
    type: content
favicon: null
title: Marnix De Cat
purpose: []
