name: Marnix De Cat
favicon: null
layout_spectrum: 0.25098
typography_spectrum: 0.60335
navigation:
  - name: Pluto & Hathor
    id: 932aaf48-6880-48b2-aec8-bb0d469cafad
    type: content
  - name: GCA
    id: 97b996bf-a214-42fb-95cb-9b29ad7fd766
    type: content
  - name: OrgaX
    id: f10743e4-c6b1-4e7f-94e4-7f45cde81707
    type: content
  - name: Bach 4 / 2
    id: 57a2b733-b3e4-4209-9730-253ec2de8ef4
    type: content
  - name: Other Projects
    id: 00b677f0-318f-4c33-b8a1-c87c13b501d1
    type: content
  - name: Rosa
    id: ab965ed4-d855-4d28-a296-108b1ae87044
    type: content
  - name: Composer
    id: bc5bd4a3-d7f9-4d20-b40d-ee6e9cfa0bfa
    type: content
  - name: Contact
    id: 7e95c9e1-b22a-407c-83f5-f527d2b1729d
    type: content
title: Marnix De Cat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-81189378-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
